name: massage_o2o_app_repository_module
description: MassageO2OApp Firebase Repository module
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  quiver: ^3.1.0  # dart's common-lang
  tuple: ^2.0.1
  intl: ^0.17.0
  logger: ^1.1.0
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.4
  json_annotation: ^4.7.0
  meta: ^1.8.0
  dio: ^4.0.6
  either_dart: ^0.3.0

  massage_o2o_app_models_module:
    git:
      url: https://github.com/weijingtai/massage_o2o_app_models_module.git
      ref: dev # dev branch
#      ref: release # branch name


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  build_runner: ^2.1.11
  json_annotation: ^4.7.0
<<<<<<< HEAD
  json_serializable: ^6.2.0
=======
  json_serializable: ^6.5.4
>>>>>>> main
  flutter_lints: ^2.0.0
  fake_cloud_firestore: ^2.0.1
  uuid: ^3.0.6
  firebase_auth: ^4.1.1





# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
#  assets:
#    - assets_dev/config.json

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
