
final ORDER_COLLECTION_NAME = "Order";
final ACTIVATED_ORDER_COLLECTION_NAME = "ActivatedOrder";
final ACHIVED_ORDER_COLLECTION_NAME = "ArchivedOrder";
final ASSIGN_COLLECTION_NAME = "Assign";

final ACTIVATED_ORDER_COLLECTION_NAME_ACTIVATED = "activated";
final ACTIVATED_ORDER_COLLECTION_NAME_ARCHIVED = "archived";

final ORDER_COLLECTION_NAME_PREPARING = "preparing";
final ORDER_COLLECTION_NAME_APPOINTMENT = "appointment";
final ORDER_COLLECTION_NAME_SERVING = "serving";
final ORDER_COLLECTION_NAME_ARCHIVED = "archived";

final SERVICES_COLLECTION_NAME = "services";
final SERVICE_ASSIGN_COLLECTION_NAME = "assigns";

final SERVICE_COLLECTION_NAME = "Service";
